/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef __GATT_DB_H
#define __GATT_DB_H

#include "sli_bt_gattdb_def.h"

extern const sli_bt_gattdb_t gattdb;

#define gattdb_generic_attribute              1
#define gattdb_service_changed_char           3
#define gattdb_database_hash                  6
#define gattdb_client_support_features        8
#define gattdb_device_name                    11
#define gattdb_device_information             14
#define gattdb_manufacturer_name_string       16
#define gattdb_system_id                      18
#define gattdb_imuble_gesture                 19
#define gattdb_gesture_data                   21
#define gattdb_battery_service                23
#define gattdb_batt_measurement               25
#define gattdb_power_source                   27
#define gattdb_power_source_type              29
#define gattdb_ota                            30
#define gattdb_ota_control                    32


#endif // __GATT_DB_H
